добавляет фильтрацию
htmlacademy-javascript/1024683-keksobooking-25 pull request #11
Opened 2022-04-01 12:21 UTC by koihoz

2022-04-02 14:51 UTC, 4err requested changes
Так не работает же :( А так логика похожа на правду.

2022-04-04 07:22 UTC, 4err requested changes
Отличная работа!

2022-04-04 07:22 UTC, 4err commented on js/api.js
> +let AllCards = [];
С заглавной буквы начинаются только перечисления и классы.

2022-04-04 07:22 UTC, 4err commented on js/filter.js
> +const COUNT_OF_CARDS = 10;
Константы должны идти до начала основного кода.

2022-04-04 07:22 UTC, 4err commented on js/filter.js
> +const checkArrayInclude = (first, second) => {
Вообще у массива есть метод includes :)

2022-04-04 07:22 UTC, 4err commented on js/filter.js
> +  if (card.offer.price <= PRICE_RANGES[price].maxprice && card.offer.price >= PRICE_RANGES[price].minprice) {return card;}
А почему `return card`? Нужно же `true/false`
Ну и исходя из этой информации, можно переделать данную строку в такое:
`return card.offer.price <= PRICE_RANGES[price].maxprice && card.offer.price >= PRICE_RANGES[price].minprice`
Мы избавляемся от if и возвращаем просто результат этого условия. Это же актуально и далее.

2022-04-04 07:22 UTC, 4err commented on js/filter.js
> +  if (card.offer.rooms === Number(rooms) || rooms === 'any' ) {return card;}
`any` Это тоже магическое значение

2022-04-04 12:23 UTC, koihoz commented on js/api.js
> +let AllCards = [];
исправил

2022-04-04 12:24 UTC, koihoz commented on js/filter.js
> +const COUNT_OF_CARDS = 10;
Исправил

2022-04-04 12:58 UTC, koihoz commented on js/filter.js
> +const checkArrayInclude = (first, second) => {
применил includes

2022-04-04 13:12 UTC, koihoz commented on js/filter.js
> +  if (card.offer.price <= PRICE_RANGES[price].maxprice && card.offer.price >= PRICE_RANGES[price].minprice) {return card;}
круто, спасибо))

2022-04-04 13:29 UTC, koihoz commented on js/filter.js
> +  if (card.offer.rooms === Number(rooms) || rooms === 'any' ) {return card;}
записал в константу

2022-04-04 14:38 UTC, merged