добавляет детали
htmlacademy-javascript/1024683-keksobooking-25 pull request #3
Opened 2022-02-28 22:50 UTC by koihoz

2022-03-01 05:15 UTC, 4err requested changes

2022-03-01 05:15 UTC, 4err commented on js/main.js
> +  const y = getRandomNumber(LOCATION.Y.MIN, LOCATION.Y.MAX, 5);
Не следует использовать однобуквенные имена переменных. Нужно переименовать во что-то более внятное. 
"5" является магическим числом. Если значение получено не как результат вычислений, это магия. Такие значения нужно вынести в константы и использовать константу. Нужно исправить здесь и далее.

2022-03-01 05:15 UTC, 4err commented on js/main.js
> +  TITLES: ['Квартира'],
Добавь разнообразия заголовкам.

2022-03-01 05:15 UTC, 4err commented on js/main.js
> +      avatar: `img/avatars/user${getRandomIntInclusive(1, 10)}.png`,
Не выполняется условие ТЗ. Значения аватаров не должны повторяться. У тебя же сейчас просто рандом. 
Также нет ведущего 0 у чисел меньше 10

2022-03-01 05:15 UTC, 4err commented on js/main.js
> +      address: [x, y],
Формат записи адреса не соответствует ТЗ.

2022-03-01 05:15 UTC, 4err commented on js/main.js
> +    location: [x, y]
Формат `location` не соответствует ТЗ

2022-03-01 05:15 UTC, 4err commented on js/main.js
> +  const arr = [];
Используй смысловые имена переменных, а не просто `arr`

2022-03-01 05:15 UTC, 4err commented on js/main.js
> +const createAdverts = () => {
Добавь количество генерируемых элементов в качестве параметра функции. Вдруг мы заходит еще несколько разных наборов данных собрать.

2022-03-01 14:04 UTC, koihoz commented on js/main.js
> +  const y = getRandomNumber(LOCATION.Y.MIN, LOCATION.Y.MAX, 5);
понял и исправил

2022-03-01 14:07 UTC, koihoz commented on js/main.js
> +  TITLES: ['Квартира'],
добавил заголовки)

2022-03-01 14:49 UTC, koihoz commented on js/main.js
> +      address: [x, y],
TЗ пункт 4.3 , исправил

2022-03-01 14:51 UTC, koihoz commented on js/main.js
> +    location: [x, y]
исправил так же как и формат записи Адреса

2022-03-01 14:52 UTC, koihoz commented on js/main.js
> +  const arr = [];
исправил

2022-03-02 05:23 UTC, 4err requested changes
Отлично! Осталось пара мелочей:
1. Все константы определяются до начала основного кода. Нужно все переменные написанные заглавными буквами перенести в начало файла. 
2. Сейчас генерируется 11 объектов, а не 10
3. Один из адресов "00", хотя они должны начинаться с единицы.

2022-03-02 15:09 UTC, merged